# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 08:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170606_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 6, 8, 6, 52, 755506, tzinfo=utc)),
        ),
    ]
